// Code generated by Ardui  no IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d6dbc4b1-e7aa-491b-98bb-a4212637d373";

const char DEVICE_KEY[]  = "QnYR6H9O2R3a@vkY9DeFZIyem";    // Secret device password

void onLastConnectedIpChange();
void onLastConneectedSSIDChange();
void onLastUpdatedChange();
void onTriggerOtaUpdateChange();

String lastConnectedIp;
String lastConneectedSSID;
String lastUpdated;
bool triggerOtaUpdate;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lastConnectedIp, READWRITE, ON_CHANGE, onLastConnectedIpChange);
  ArduinoCloud.addProperty(lastConneectedSSID, READWRITE, ON_CHANGE, onLastConneectedSSIDChange);
  ArduinoCloud.addProperty(lastUpdated, READWRITE, ON_CHANGE, onLastUpdatedChange);
  ArduinoCloud.addProperty(triggerOtaUpdate, READWRITE, ON_CHANGE, onTriggerOtaUpdateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection;
